apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-testing
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nxing-test
        image: nginx:latest
        ports:
        - containerPort: 80
