apiVersion: apps/v1
kind: Deployment
metadata:
  name: root-only-nginx
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      serviceAccountName: dev-csos-admins
      containers:
      - name: root-onyl-nginx-container
        image: nginx:latest
        ports:
        - containerPort: 80
